# Import libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from IPython.core.debugger import set_trace
import json
from matplotlib import colors
from ast import literal_eval

# Load data

In [2]:
# psynet 11
fname = "manu-test-ising1"
fname = "singing-musicians-June-2026"
fname = "singing-musicians-July-2026"

PATH = f"data/{fname}/"
nodes = pd.read_csv(PATH + "CustomNode.csv", low_memory=False)
# networks = pd.read_csv(PATH + "CustomNetwork.csv", low_memory=False) # old psynet
trials = pd.read_csv(PATH + "CustomTrial.csv", low_memory=False)

In [3]:
print(nodes)

     vars    id        creation_time  failed failed_reason time_of_death  \
0      {}    17  2026-06-17 07:49:34   False           NaN           NaN
1      {}    18  2026-06-17 07:49:34   False           NaN           NaN
2      {}    19  2026-06-17 07:49:34   False           NaN           NaN
3      {}    20  2026-06-17 07:49:34   False           NaN           NaN
4      {}    21  2026-06-17 07:49:34   False           NaN           NaN
...   ...   ...                  ...     ...           ...           ...
3487   {}  3504  2026-07-26 18:32:43   False           NaN           NaN
3488   {}  3505  2026-07-26 18:32:57   False           NaN           NaN
3489   {}  3506  2026-07-26 18:33:23   False           NaN           NaN
3490   {}  3507  2026-07-26 18:33:42   False           NaN           NaN
3491   {}  3508  2026-07-26 18:33:56   False           NaN           NaN

             type  network_id  participant_id   trial_maker_id  ... parent_id  \
0     TrialSource          17               1  imitation_chain  ...       NaN
1     TrialSource          18               1  imitation_chain  ...       NaN
2     TrialSource          19               1  imitation_chain  ...       NaN
3     TrialSource          20               1  imitation_chain  ...       NaN
4     TrialSource          21               1  imitation_chain  ...       NaN
...           ...         ...             ...              ...  ...       ...
3487   CustomNode         387             104  imitation_chain  ...    3500.0
3488   CustomNode         388             104  imitation_chain  ...    3502.0
3489   CustomNode         388             104  imitation_chain  ...    3505.0
3490   CustomNode         387             104  imitation_chain  ...    3504.0
3491   CustomNode         390             104  imitation_chain  ...    3503.0

                                                   seed  \
0     {"register": "high", "reference_pitch": 61.513...
1     {"register": "high", "reference_pitch": 62.533...
2     {"register": "high", "reference_pitch": 61.719...
3     {"register": "high", "reference_pitch": 61.820...
4     {"register": "high", "reference_pitch": 61.488...
...                                                 ...
3487  {"reference_pitch": 59.83554718713076, "regist...
3488  {"reference_pitch": 60.856601707676425, "regis...
3489  {"reference_pitch": 61.44546019005024, "regist...
3490  {"reference_pitch": 59.61770022391349, "regist...
3491  {"reference_pitch": 59.29918452918062, "regist...

                                             definition  context  \
0     {"register": "high", "reference_pitch": 61.513...      NaN
1     {"register": "high", "reference_pitch": 62.533...      NaN
2     {"register": "high", "reference_pitch": 61.719...      NaN
3     {"register": "high", "reference_pitch": 61.820...      NaN
4     {"register": "high", "reference_pitch": 61.488...      NaN
...                                                 ...      ...
3487  {"reference_pitch": 59.83554718713076, "regist...      NaN
3488  {"reference_pitch": 60.856601707676425, "regis...      NaN
3489  {"reference_pitch": 61.44546019005024, "regist...      NaN
3490  {"reference_pitch": 59.61770022391349, "regist...      NaN
3491  {"reference_pitch": 59.29918452918062, "regist...      NaN

      participant_group    block  propagate_failure  n_viable_trials  \
0               default  default              False                1
1               default  default              False                1
2               default  default              False                1
3               default  default              False                1
4               default  default              False                1
...                 ...      ...                ...              ...
3487            default  default              False                1
3488            default  default              False                1
3489            default  default              False                0
3490            default  default              False                0
3491            default  default              False                0

           class  object_type
0     CustomNode         Node
1     CustomNode         Node
2     CustomNode         Node
3     CustomNode         Node
4     CustomNode         Node
...          ...          ...
3487  CustomNode         Node
3488  CustomNode         Node
3489  CustomNode         Node
3490  CustomNode         Node
3491  CustomNode         Node

[3492 rows x 33 columns]

In [4]:
# filter nodes
node_data = nodes
node_data = node_data[node_data["failed"] == False]
node_data = node_data[["id", "network_id", "degree", "trial_maker_id", "definition", "seed"]]
node_data = node_data.sort_values(["network_id", "degree"])
node_data["definition"].iloc[1]

print(node_data['definition'])

0       {"register": "high", "reference_pitch": 61.513...
8       {"reference_pitch": 59.442037702692495, "regis...
11      {"reference_pitch": 61.5932768305512, "registe...
18      {"reference_pitch": 63.03794404910124, "regist...
22      {"reference_pitch": 59.76154684762448, "regist...
                              ...
3478    {"reference_pitch": 61.08426073986259, "regist...
3481    {"reference_pitch": 62.49672216453698, "regist...
3484    {"reference_pitch": 59.814687916848555, "regis...
3486    {"reference_pitch": 63.298596816011916, "regis...
3491    {"reference_pitch": 59.29918452918062, "regist...
Name: definition, Length: 3319, dtype: object

# Preprocess data

In [5]:
# filter nodes
node_data = nodes
node_data = node_data[node_data["failed"] == False]
node_data = node_data[["id", "network_id", "degree", "trial_maker_id", "definition", "seed"]]
node_data = node_data.sort_values(["network_id", "degree"])

# process node definition
mel_id = []
# register = []
trial_type = []
target_pitches = []
target_intervals = []
reference_pitch = []
target_note_durations = []

for i in range(len(node_data)):
    print()
    # definition = node_data["definition"].to_numpy()[i]
    # definition = literal_eval(definition)
    # definition = [d["content"] for d in definition if d["is_center"]][0]

    definition_str = node_data["definition"].iloc[i]  # Access the string directly
    print(definition_str)
    definition = json.loads(definition_str)  # Parse JSON string into dictionary
    # definition = [d["content"] for d in definition if d["is_center"]][0]
    
    # mel_id.append(definition["mel_id"])
    # register.append(definition["register"])
    trial_type.append(definition["trial_type"])
    target_pitches.append(definition["target_pitches"])
    reference_pitch.append(definition["reference_pitch"])
    target_intervals.append(definition["target_intervals"])

# node_data["mel_id"] = mel_id
# node_data["register"] = register
node_data["trial_type"] = trial_type
node_data["target_pitches"] = target_pitches
node_data["reference_pitch"] = reference_pitch
node_data["target_intervals"] = target_intervals

{"register": "high", "reference_pitch": 61.51365945675623, "max_interval2reference": 10, "max_interval_size": 5.5, "target_pitches": [62.26776695793315, 59.31690312168399, 67.74881709916347], "target_intervals": [-2.9508638362491553, 8.431913977479482], "target_intervals2reference": [0.754107501176918, -2.196756335072237, 6.235157642407245], "num_target_pitches": 3, "trial_type": "source_trial", "reference_mode": "pitch_mode"}

{"reference_pitch": 59.442037702692495, "register": "high", "target_pitches": [58.675315655120436, 56.67578458605753, 65.71309774921647], "target_intervals": [-1.999531069062904, 9.037313163158935], "target_intervals2reference": [-0.7667220475720598, -2.7662531166349638, 6.271060046523971], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 61.5932768305512, "register": "high", "target_pitches": [59.80697032178534, 58.13777038659859, 67.2834132422523], "target_intervals": [-1.6691999351867537, 9.145642855653705], "target_intervals2reference": [-1.786306508765854, -3.4555064439526078, 5.690136411701097], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 63.03794404910124, "register": "high", "target_pitches": [58.94231446422989, 57.36454643446263, 68.73165361345107], "target_intervals": [-1.577768029767256, 11.367107178988434], "target_intervals2reference": [-4.095629584871354, -5.67339761463861, 5.693709564349824], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 59.76154684762448, "register": "high", "target_pitches": [53.81551845974534, 52.68381431046352, 64.98075264671147], "target_intervals": [-1.1317041492818234, 12.296938336247955], "target_intervals2reference": [-5.946028387879139, -7.077732537160962, 5.219205799086993], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 59.548640619548685, "register": "high", "target_pitches": [54.02617767528107, 52.111899507628834, 64.35505626786396], "target_intervals": [-1.9142781676522347, 12.243156760235124], "target_intervals2reference": [-5.522462944267616, -7.436741111919851, 4.806415648315273], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 62.528483029865285, "register": "high", "target_pitches": [56.71527326349905, 54.58286138069516, 66.61809163569825], "target_intervals": [-2.1324118828038934, 12.0352302550031], "target_intervals2reference": [-5.813209766366235, -7.945621649170128, 4.0896086058329715], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 62.25130361782004, "register": "high", "target_pitches": [55.427670965281216, 53.4137975732236, 65.61651289197597], "target_intervals": [-2.0138733920576186, 12.202715318752375], "target_intervals2reference": [-6.8236326525388264, -8.837506044596445, 3.36520927415593], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 58.93463100962565, "register": "high", "target_pitches": [50.97332816007881, 49.94197569129565, 62.11532720393636], "target_intervals": [-1.0313524687831546, 12.173351512640707], "target_intervals2reference": [-7.96130284954684, -8.992655318329994, 3.1806961943107126], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 61.464895719495075, "register": "high", "target_pitches": [54.83930118392046, 52.30814113143684, 64.16657893328741], "target_intervals": [-2.531160052483621, 11.858437801850577], "target_intervals2reference": [-6.6255945355746135, -9.156754588058234, 2.701683213792343], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 59.59437331566868, "register": "high", "target_pitches": [51.458569977498506, 49.86744149235792, 62.53518378330123], "target_intervals": [-1.5911284851405867, 12.667742290943309], "target_intervals2reference": [-8.135803338170177, -9.726931823310764, 2.940810467632545], "num_target_pitches": 3, "trial_type": "node_trial"}

{"register": "high", "reference_pitch": 62.53369778164291, "max_interval2reference": 10, "max_interval_size": 5.5, "target_pitches": [64.64621193675086, 63.98195354666511, 54.467243038389014], "target_intervals": [-0.6642583900857488, -9.514710508276096], "target_intervals2reference": [2.1125141551079523, 1.4482557650222034, -8.066454743253892], "num_target_pitches": 3, "trial_type": "source_trial", "reference_mode": "pitch_mode"}

{"reference_pitch": 58.786599416361064, "register": "high", "target_pitches": [59.97989430724822, 59.32067092093444, 50.337769068178005], "target_intervals": [-0.6592233863137835, -8.982901852756434], "target_intervals2reference": [1.1932948908871595, 0.5340715045733759, -8.448830348183058], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 61.28240827609331, "register": "high", "target_pitches": [61.57951322016172, 60.82082886280923, 52.78706859232628], "target_intervals": [-0.7586843573524931, -8.03376027048295], "target_intervals2reference": [0.2971049440684155, -0.4615794132840776, -8.495339683767028], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 62.97268908003474, "register": "high", "target_pitches": [63.00606371229204, 61.18205754175921, 53.279486765569516], "target_intervals": [-1.824006170532833, -7.902570776189691], "target_intervals2reference": [0.0333746322572992, -1.7906315382755338, -9.693202314465225], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 59.188259835688, "register": "high", "target_pitches": [58.4235617686862, 56.46539480982514, 48.170745762652174], "target_intervals": [-1.9581669588610566, -8.294649047172967], "target_intervals2reference": [-0.7646980670018024, -2.722865025862859, -11.017514073035827], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 62.09452707959518, "register": "high", "target_pitches": [61.71894049521578, 59.175529348975246, 51.77043539730035], "target_intervals": [-2.543411146240537, -7.405093951674893], "target_intervals2reference": [-0.3755865843793984, -2.9189977306199353, -10.324091682294828], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 59.62883887088346, "register": "high", "target_pitches": [57.75642836233592, 56.4788989239786, 48.830324156076166], "target_intervals": [-1.2775294383573197, -7.648574767902431], "target_intervals2reference": [-1.8724105085475458, -3.1499399469048655, -10.798514714807297], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 62.27945728294269, "register": "high", "target_pitches": [60.08356046559806, 59.95146988195845, 51.59900372026694], "target_intervals": [-0.13209058363960935, -8.35246616169151], "target_intervals2reference": [-2.195896817344625, -2.3279874009842345, -10.680453562675744], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 59.043487515331186, "register": "high", "target_pitches": [56.37216087279512, 56.4582641275427, 47.978514610676235], "target_intervals": [0.0861032547475773, -8.479749516866462], "target_intervals2reference": [-2.6713266425360658, -2.5852233877884885, -11.064972904654951], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 62.48411199847183, "register": "high", "target_pitches": [59.23208298626353, 59.613587001430794, 52.324942596386045], "target_intervals": [0.3815040151672662, -7.288644405044749], "target_intervals2reference": [-3.252029012208304, -2.870524997041038, -10.159169402085787], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 61.98150295390974, "register": "high", "target_pitches": [58.150888812641114, 58.46983042189393, 51.05152952817514], "target_intervals": [0.31894160925281767, -7.4183008937187935], "target_intervals2reference": [-3.830614141268626, -3.511672532015808, -10.929973425734602], "num_target_pitches": 3, "trial_type": "node_trial"}

{"register": "high", "reference_pitch": 61.71967998354399, "max_interval2reference": 10, "max_interval_size": 5.5, "target_pitches": [62.82499009978372, 60.09026540053221, 53.53662561118896], "target_intervals": [-2.734724699251508, -6.553639789343251], "target_intervals2reference": [1.1053101162397283, -1.6294145830117799, -8.18305437235503], "num_target_pitches": 3, "trial_type": "source_trial", "reference_mode": "pitch_mode"}

{"reference_pitch": 59.26175792588361, "register": "high", "target_pitches": [59.94681986228326, 56.99656315050406, 50.41455272689299], "target_intervals": [-2.950256711779204, -6.582010423611067], "target_intervals2reference": [0.6850619363996557, -2.2651947753795483, -8.847205198990615], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 60.195396878387236, "register": "high", "target_pitches": [60.88591245833128, 58.14351986900297, 51.388072222213765], "target_intervals": [-2.742392589328311, -6.755447646789207], "target_intervals2reference": [0.6905155799440479, -2.0518770093842633, -8.80732465617347], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 59.753628871948344, "register": "high", "target_pitches": [59.66005734397412, 56.68073295471393, 50.21415969178747], "target_intervals": [-2.979324389260185, -6.46657326292646], "target_intervals2reference": [-0.09357152797422685, -3.072895917234412, -9.539469180160872], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 63.26336621346334, "register": "high", "target_pitches": [62.51872873031558, 60.812483416569485, 53.611504689715055], "target_intervals": [-1.706245313746095, -7.20097872685443], "target_intervals2reference": [-0.7446374831477627, -2.4508827968938576, -9.651861523748288], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 62.92646605204262, "register": "high", "target_pitches": [61.45137830126004, 59.88212327050331, 51.861416895519824], "target_intervals": [-1.569255030756736, -8.020706374983483], "target_intervals2reference": [-1.4750877507825777, -3.0443427815393136, -11.065049156522797], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 62.44275221371091, "register": "high", "target_pitches": [60.09079507919675, 59.246871001896764, 50.74202913795029], "target_intervals": [-0.8439240772999881, -8.504841863946474], "target_intervals2reference": [-2.3519571345141586, -3.1958812118141466, -11.70072307576062], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 62.5248664495279, "register": "high", "target_pitches": [59.77299934358197, 58.951562917448605, 50.74041621656606], "target_intervals": [-0.8214364261333671, -8.211146700882544], "target_intervals2reference": [-2.7518671059459265, -3.5733035320792936, -11.784450232961838], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 61.03320439096136, "register": "high", "target_pitches": [56.997001249156796, 55.9654705795708, 48.57051147352127], "target_intervals": [-1.0315306695859974, -7.3949591060495266], "target_intervals2reference": [-4.036203141804563, -5.067733811390561, -12.462692917440087], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 58.809396678419056, "register": "high", "target_pitches": [54.57287163951967, 53.70713248507453, 46.64975487632082], "target_intervals": [-0.8657391544451372, -7.057377608753711], "target_intervals2reference": [-4.236525038899387, -5.102264193344524, -12.159641802098236], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 63.061875503950155, "register": "high", "target_pitches": [60.57268983478599, 56.897277325670636, 51.175128568049495], "target_intervals": [-3.675412509115354, -5.722148757621142], "target_intervals2reference": [-2.489185669164165, -6.164598178279519, -11.88674693590066], "num_target_pitches": 3, "trial_type": "node_trial"}

{"register": "high", "reference_pitch": 61.82094086608705, "max_interval2reference": 10, "max_interval_size": 5.5, "target_pitches": [53.10031376286065, 71.78457839198316, 53.065241096974226], "target_intervals": [18.68426462912251, -18.719337295008934], "target_intervals2reference": [-8.720627103226398, 9.963637525896111, -8.755699769112823], "num_target_pitches": 3, "trial_type": "source_trial", "reference_mode": "pitch_mode"}

{"reference_pitch": 63.24683812389488, "register": "high", "target_pitches": [54.02901769741393, 73.40842169669384, 54.2540930043468], "target_intervals": [19.37940399927991, -19.154328692347036], "target_intervals2reference": [-9.217820426480955, 10.161583572798953, -8.992745119548083], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 62.191388142606584, "register": "high", "target_pitches": [52.14807078284329, 71.93459500669016, 52.43566251900895], "target_intervals": [19.78652422384686, -19.498932487681202], "target_intervals2reference": [-10.043317359763293, 9.743206864083568, -9.755725623597634], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 60.63447013831965, "register": "high", "target_pitches": [49.89134101964664, 70.4649119965795, 50.500622857204725], "target_intervals": [20.57357097693287, -19.964289139374785], "target_intervals2reference": [-10.74312911867301, 9.83044185825986, -10.133847281114924], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 60.56137807078828, "register": "high", "target_pitches": [51.7978618815359, 70.4225912031078, 50.44740172544554], "target_intervals": [18.624729321571905, -19.97518947766227], "target_intervals2reference": [-8.763516189252378, 9.861213132319527, -10.113976345342742], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 63.0812906932068, "register": "high", "target_pitches": [58.0035627881008, 73.10285734792939, 53.247766594759526], "target_intervals": [15.099294559828579, -19.855090753169854], "target_intervals2reference": [-5.077727905106002, 10.021566654722577, -9.833524098447278], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 62.90579952832167, "register": "high", "target_pitches": [52.15606964712501, 72.7093247594953, 52.745785988028715], "target_intervals": [20.553255112370294, -19.963538771466588], "target_intervals2reference": [-10.749729881196664, 9.80352523117363, -10.160013540292958], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 60.96289830810466, "register": "high", "target_pitches": [49.95705474447679, 70.586736687256, 50.45824753658651], "target_intervals": [20.629681942779214, -20.128489150669495], "target_intervals2reference": [-11.00584356362787, 9.623838379151344, -10.50465077151815], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 59.73010884854641, "register": "high", "target_pitches": [48.91672719818231, 69.17109344718273, 49.39287115890338], "target_intervals": [20.254366249000412, -19.778222288279338], "target_intervals2reference": [-10.8133816503641, 9.440984598636312, -10.337237689643025], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 58.75423656868811, "register": "high", "target_pitches": [48.33182915303255, 67.7031576031741, 48.82202315533271], "target_intervals": [19.371328450141547, -18.88113444784139], "target_intervals2reference": [-10.422407415655556, 8.948921034485991, -9.932213413355399], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 61.832966030012024, "register": "high", "target_pitches": [51.92619552411364, 70.38227619125783, 52.17758549234995], "target_intervals": [18.456080667144192, -18.204690698907882], "target_intervals2reference": [-9.906770505898386, 8.549310161245806, -9.655380537662076], "num_target_pitches": 3, "trial_type": "node_trial"}

{"register": "high", "reference_pitch": 61.4882202146343, "max_interval2reference": 10, "max_interval_size": 5.5, "target_pitches": [57.8595991344324, 52.19261276690406, 60.42581632320747], "target_intervals": [-5.666986367528338, 8.233203556303408], "target_intervals2reference": [-3.6286210802019028, -9.29560744773024, -1.0624038914268326], "num_target_pitches": 3, "trial_type": "source_trial", "reference_mode": "pitch_mode"}

{"reference_pitch": 60.420395421245935, "register": "high", "target_pitches": [56.535346366754005, 50.41290718045282, 58.80444498209806], "target_intervals": [-6.122439186301186, 8.391537801645242], "target_intervals2reference": [-3.8850490544919296, -10.007488240793116, -1.6159504391478734], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 59.374679730940606, "register": "high", "target_pitches": [55.382304010535634, 49.401646451671226, 57.537414955874155], "target_intervals": [-5.980657558864408, 8.135768504202929], "target_intervals2reference": [-3.992375720404972, -9.97303327926938, -1.8372647750664513], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 58.94693145088397, "register": "high", "target_pitches": [54.87995467618893, 49.37843710786896, 56.77242501640299], "target_intervals": [-5.501517568319969, 7.393987908534029], "target_intervals2reference": [-4.066976774695043, -9.568494343015011, -2.174506434480982], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 63.47438557596645, "register": "high", "target_pitches": [59.42020982910455, 54.72580059778525, 60.99505543169706], "target_intervals": [-4.694409231319298, 6.269254833911809], "target_intervals2reference": [-4.054175746861901, -8.7485849781812, -2.4793301442693902], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 61.94168965894836, "register": "high", "target_pitches": [56.48704638406656, 50.973874062089834, 59.187427952521546], "target_intervals": [-5.513172321976725, 8.213553890431712], "target_intervals2reference": [-5.4546432748818034, -10.967815596858529, -2.754261706426817], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 61.40654237993066, "register": "high", "target_pitches": [55.58105425293715, 49.87717068959615, 58.114648744315524], "target_intervals": [-5.703883563341002, 8.237478054719375], "target_intervals2reference": [-5.825488126993513, -11.529371690334514, -3.291893635615139], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 62.486942522139465, "register": "high", "target_pitches": [56.33887161289307, 51.206188056204304, 58.679000289435635], "target_intervals": [-5.132683556688768, 7.4728122332313305], "target_intervals2reference": [-6.1480709092463925, -11.28075446593516, -3.80794223270383], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 59.93858325038836, "register": "high", "target_pitches": [53.812477332308696, 48.32128108708436, 55.946434871256834], "target_intervals": [-5.491196245224337, 7.6251537841724755], "target_intervals2reference": [-6.126105918079666, -11.617302163304004, -3.992148379131528], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 59.338166034732915, "register": "high", "target_pitches": [52.58036417555809, 48.3326661921747, 54.696009072510456], "target_intervals": [-4.247697983383389, 6.3633428803357575], "target_intervals2reference": [-6.757801859174826, -11.005499842558216, -4.642156962222458], "num_target_pitches": 3, "trial_type": "node_trial"}

{"reference_pitch": 59.47730629637922, "register": "high", "target_pitches": [51.93356230656862, 48.58904677261943, 54.773785624246834], "target_intervals": [-3.3445155339491848, 6.184738851627401], "target_intervals2reference": [-7.543743989810601, -10.888259523759785, -4.703520672132385], "num_target_pitches": 3, "trial_type": "node_trial"}

{"register": "high", "reference_pitch": 62.94673507555914, "max_interval2reference": 10, "max_interval_size": 5.5, "target_pitches": [67.57642840143899, 68.92081104949295, 70.36033732375493], "target_intervals": [1.3443826480539656, 1.4395262742619792], "target_intervals2reference": [4.629693325879849, 5.9740759739338145, 7.413602248195794], "num_target_pitches": 3, "trial_type": "source_trial", "reference_mode": "pitch_mode"}


In [6]:
node_data

,id,network_id,degree,trial_maker_id,definition,seed,trial_type,target_pitches,reference_pitch,target_intervals
0,17,17,0,imitation_chain,"{""register"": ""high"", ""reference_pitch"": 61.513...","{""register"": ""high"", ""reference_pitch"": 61.513...",source_trial,"[62.26776695793315, 59.31690312168399, 67.7488...",61.513659,"[-2.9508638362491553, 8.431913977479482]"
8,25,17,1,imitation_chain,"{""reference_pitch"": 59.442037702692495, ""regis...","{""reference_pitch"": 59.442037702692495, ""regis...",node_trial,"[58.675315655120436, 56.67578458605753, 65.713...",59.442038,"[-1.999531069062904, 9.037313163158935]"
11,28,17,2,imitation_chain,"{""reference_pitch"": 61.5932768305512, ""registe...","{""reference_pitch"": 61.5932768305512, ""registe...",node_trial,"[59.80697032178534, 58.13777038659859, 67.2834...",61.593277,"[-1.6691999351867537, 9.145642855653705]"
18,35,17,3,imitation_chain,"{""reference_pitch"": 63.03794404910124, ""regist...","{""reference_pitch"": 63.03794404910124, ""regist...",node_trial,"[58.94231446422989, 57.36454643446263, 68.7316...",63.037944,"[-1.577768029767256, 11.367107178988434]"
22,39,17,4,imitation_chain,"{""reference_pitch"": 59.76154684762448, ""regist...","{""reference_pitch"": 59.76154684762448, ""regist...",node_trial,"[53.81551845974534, 52.68381431046352, 64.9807...",59.761547,"[-1.1317041492818234, 12.296938336247955]"
...,...,...,...,...,...,...,...,...,...,...
3478,3495,390,6,imitation_chain,"{""reference_pitch"": 61.08426073986259, ""regist...","{""reference_pitch"": 61.08426073986259, ""regist...",node_trial,"[64.33417418903008, 71.55188203764706, 69.5993...",61.084261,"[7.217707848616982, -1.9524964559052762]"
3481,3498,390,7,imitation_chain,"{""reference_pitch"": 62.49672216453698, ""regist...","{""reference_pitch"": 62.49672216453698, ""regist...",node_trial,"[65.73622347951517, 72.91431263840802, 70.8485...",62.496722,"[7.1780891588928455, -2.0657154746104283]"
3484,3501,390,8,imitation_chain,"{""reference_pitch"": 59.814687916848555, ""regis...","{""reference_pitch"": 59.814687916848555, ""regis...",node_trial,"[62.76431241023546, 70.19097474225259, 67.8975...",59.814688,"[7.4266623320171234, -2.2934709373805333]"
3486,3503,390,9,imitation_chain,"{""reference_pitch"": 63.298596816011916, ""regis...","{""reference_pitch"": 63.298596816011916, ""regis...",node_trial,"[65.90751979742541, 73.50753893298048, 71.6393...",63.298597,"[7.600019135555073, -1.8681810795361287]"
3491,3508,390,10,imitation_chain,"{""reference_pitch"": 59.29918452918062, ""regist...","{""reference_pitch"": 59.29918452918062, ""regist...",node_trial,"[62.254522706609414, 69.80086962563689, 67.157...",59.299185,"[7.546346919027485, -2.6434493157300523]"

# Export node data to csv

In [9]:
node_data.to_csv(f"{fname}_node_data.csv")

# Trial level data

In [10]:
# filter trials
trial_data = trials
trial_data = trial_data[trial_data["failed"] == False]

degrees = []

for i in range(len(trial_data)):
    current_node_id = trial_data.iloc[i]["origin_id"]
    current_nodes = node_data[node_data["id"] == current_node_id]
    current_degree = current_nodes["degree"].to_numpy()[0]
    # answer = d['listen_and_rate_trial_seed']['valence']
    # current_vertex_id = current_nodes["vertex_id"].to_numpy()[0]
    # current_dependent_vertex_ids = current_nodes["dependent_vertex_ids"].to_numpy()[0]
    degrees.append(current_degree)
    # vertex_ids.append(current_vertex_id)
    # dependent_vertex_ids.append(current_dependent_vertex_ids)

trial_data["degree"] = degrees

trial_data = trial_data[["id", "network_id", "degree", "trial_maker_id", "origin_id", "participant_id", "analysis"]]
trial_data = trial_data.sort_values(["network_id", "degree"])

IndexError: index 0 is out of bounds for axis 0 with size 0

In [12]:
trial_data

,id,network_id,degree,trial_maker_id,origin_id,participant_id,analysis
4,17,17,0,imitation_chain,17,3,"{""failed"": false, ""reason"": ""All good"", ""regis..."
6,19,17,1,imitation_chain,26,3,"{""failed"": false, ""reason"": ""All good"", ""regis..."
12,25,17,2,imitation_chain,28,3,"{""failed"": false, ""reason"": ""All good"", ""regis..."
18,31,17,3,imitation_chain,34,3,"{""failed"": false, ""reason"": ""All good"", ""regis..."
20,33,17,4,imitation_chain,40,3,"{""failed"": false, ""reason"": ""All good"", ""regis..."
...,...,...,...,...,...,...,...
1274,1560,141,5,imitation_chain,1097,32,"{""failed"": false, ""reason"": ""All good"", ""regis..."
1279,1565,141,6,imitation_chain,1103,32,"{""failed"": false, ""reason"": ""All good"", ""regis..."
1287,1573,141,7,imitation_chain,1108,32,"{""failed"": false, ""reason"": ""All good"", ""regis..."
1290,1576,141,8,imitation_chain,1114,32,"{""failed"": false, ""reason"": ""All good"", ""regis..."
1292,1578,141,9,imitation_chain,1117,32,"{""failed"": false, ""reason"": ""All good"", ""regis..."

# Export trial data to csv

In [13]:
trial_data.to_csv(f"{fname}_trial_data.csv")

# Experiment Cost and Demographics

In [14]:
participants = pd.read_csv(PATH + "participant.csv", low_memory=False)

In [15]:
valid_participants = participants[participants["complete"] == True]
valid_participants = valid_participants[valid_participants["failed"] == False]
experiment_summary = {
    "N_participants": valid_participants.shape[0],
    "cost": participants["base_pay"].sum() + participants["bonus"].sum()
}

experiment_summary

{'N_participants': 24, 'cost': 0.0}